const appRootDir = require('app-root-dir').get()
const fs = require('fs')
const path = require('path')
const _ = require('lodash')

const widgetConfig = require(path.join(appRootDir, 'build', 'config', 'widget.config'))
const defaultWidgetConfig = require('../config/default.widget.config')

// TODO describe the necessity of this madness
// gulp -> jest -> your test file.
// multiple child process hops. Hard to pass info. Use temp file to pass from gulp -> your test
// this file is generated by src/build/tasks/jestSnapshotTests.js which is typically run by the gulp process, and the file is then available for the process actually executing the .jest.test files
// a command line arg approach is not possible because jest will NOT propagate any command line args to its child processes
const dynamicSnapshotConfigPath = path.join(appRootDir, '.tmp', 'snapshot_dynamic_config.json')
const dynamicSnapshotConfigExists = fs.existsSync(dynamicSnapshotConfigPath)
const dynamicSnapshotConfig = (dynamicSnapshotConfigExists)
  ? require(path.join(appRootDir, '.tmp', 'snapshot_dynamic_config'))
  : {}

module.exports = _.defaultsDeep(
  { basePath: appRootDir },
  { snapshotTesting: dynamicSnapshotConfig },
  widgetConfig,
  defaultWidgetConfig
)
