const path = require('path')
const serveStatic = require('serve-static')
const serveIndex = require('serve-index')
const connect = require('connect')
const connectLiveReload = require('connect-livereload')
const httpServer = require('http')
const yargs = require('yargs')
const { registerTeardown } = require('../../lib/teardown')
const { basePath } = require('../../lib/widgetConfig')

module.exports = () => {
  return function (done) {
    const port = yargs.parse().port || 9000
    const liveReloadPort = 35729 + (parseInt(port) - 9000)

    const browserDirectory = path.join(basePath, 'browser')
    const app = connect()
      .use(connectLiveReload({ port: liveReloadPort }))
      // browser is a directory of compiled JS/HTML/CSS to serve. It is generated by the core task
      .use(serveStatic(browserDirectory))
      .use(serveIndex(browserDirectory))

    const server = httpServer.createServer(app)

    // NB this listening server is why the gulp build could not exit on its own, and why
    // takeSnapshotsForEachTestDefinition used to force the issue with process.exit in a setTimeout.
    // Registering the handle lets the runner close it and exit normally, which is what removed the need
    // for testVisual to be the last task in a sequence.
    registerTeardown('connect web server', () => new Promise(resolve => server.close(resolve)))

    server.listen(port).on('listening', function () {
      console.log(`Started connect web server on http://localhost:${port} (live reload port: ${liveReloadPort})`)
      done()
    })
  }
}
