const serveStatic = require('serve-static')
const serveIndex = require('serve-index')
const connect = require('connect')
const connectLiveReload = require('connect-livereload')
const httpServer = require('http')
const cliArgs = require('yargs').argv

module.exports = function (gulp) {
  return function (done) {
    const port = cliArgs.port || 9000
    const liveReloadPort = 35729 + (parseInt(port) - 9000)

    const app = connect()
      .use(connectLiveReload({ port: liveReloadPort }))
      // browser is a directory of compiled JS/HTML/CSS to serve. It is generated by the core task
      .use(serveStatic('browser'))
      .use(serveIndex('browser'))

    httpServer.createServer(app)
      .listen(port)
      .on('listening', function () {
        console.log(`Started connect web server on http://localhost:${port} (live reload port: ${liveReloadPort})`)
        done()
      })
  }
}
